default: &default
  adapter: 'mysql2'

development: &development
  <<: *default
  host: <%= ENV['TINYSIS_HOST'] %>
  database: <%= ENV['TINYSIS_DATABASE'] %>
  username: <%= ENV['TINYSIS_USER'] %>
  password: <%= ENV['TINYSIS_PASSWORD'] %>

test:
  <<: *default
  database: 'tinysis_test'
  username: 'tinysis_test'
  password: 'tinysis_test'

production:
  <<: *development
